nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5174', 'http://127.0.0.1:5174']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        max_age: 3600

    paths:
        '^/api/':
            allow_origin: ['http://localhost:5174', 'http://127.0.0.1:5174']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'OPTIONS']
            max_age: 3600
