version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /var/www/html/back
    volumes:
      - .:/var/www/html/back

    depends_on:
      - database
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    environment:
      DATABASE_URL: "pgsql://root:latchim@database:5432/homeez?serverVersion=16&charset=utf8"
    tty: true
    stdin_open: true

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # Port SMTP
      - "8025:8025" # Interface web (http://localhost:8025)

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-homeez}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-latchim}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-homeez}", "-U", "${POSTGRES_USER:-root}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: symfony_adminer
    restart: always
    ports:
      - "8081:8080" # on change le port pour Ã©viter conflit avec PHP
    depends_on:
      - database



volumes:
  database_data:

