name: Homee'z CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Symfony API
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: app
          POSTGRES_USER: elias
          POSTGRES_PASSWORD: elias
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U elias -d app"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Composer dependencies
        run: |
          cd back
          composer install --no-interaction --no-progress --prefer-dist --ignore-platform-req=php

      - name: Setup env
        run: |
          cd back
          cp .env .env.test
          sed -i "s|DATABASE_URL=.*|DATABASE_URL=postgresql://elias:elias@127.0.0.1:5432/app?serverVersion=16|" .env.test

      - name: Run migrations
        run: |
          cd back
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run tests
        run: |
          cd back
          php bin/phpunit

  frontend:
    name: Vue Front
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd front
          npm install


      - name: Build app
        run: |
          cd front
          npm run build-only
